### PR TITLE
tidy xiview.py

### PR DESCRIPTION
**Pull request by colin-combe**
### **User description**
tidies up xiview.py by removing duplicate code. Should be OK to merge

@sureshhewabi - i've got following questions about tidying up this project:
- seems like we don't have any versioning of the API?
- is process_dataset.py really needed in there?
- is the fastapi and sessio import needed at top of xiview.py
- i'm not sure how that models.Upload import works? The models directory in this proj is empty?

___

### **PR Type**
enhancement

___

### **Description**
- Removed unused imports and redundant code to tidy up the `xiview.py` file.
- Refactored the database query execution into a reusable `execute_query` function to reduce code duplication and improve maintainability.
- Simplified and consolidated logic for endpoints handling metadata, matches, peptides, and proteins, improving code readability and performance.
- Enhanced error handling and logging for database operations to provide better insights during failures.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>xiview.py</strong><dd><code>Refactor and optimize xiview.py for better performance</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

app/routes/xiview.py

<li>Removed unused imports and redundant code.<br> <li> Refactored database query execution into a reusable function.<br> <li> Simplified and consolidated endpoint logic for metadata, matches, <br>peptides, and proteins.<br> <li> Improved error handling and logging for database operations.<br>

</details>

  </td>
  <td><a href="https://github.com/PRIDE-Archive/xiview-api/pull/17/files#diff-c13a328ae890ae2ee4580ed06b30570f529b9ee26865828c9f30f674ce2dedd1">+111/-479</a></td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by colin-combe** [comment]
@sureshhewabi - i think the security concern raised by PR-Agent thingy must be about the `visualisations` end point? (your one, that's written using sqlalchemy orm). I think we should refactor that.

I don't really understand the PR-Agent comment about using a context manager

**Comment by colin-combe** [comment]
...i think it's right about that context manager thing

**Comment by colin-combe** [comment]
@sureshhewabi - i think this context manager thing might be connected to the behaviour i was pointing out where things seemed blocked

**Comment by sureshhewabi** [comment]
> @sureshhewabi - i think this context manager thing might be connected to the behaviour i was pointing out where things seemed blocked

Did you try with the suggested code?

**Comment by colin-combe** [comment]
i did and it didn't work, i also asked chatpgt about it and it agreed but the code it suggested also didn't work.
i think there's something more fundamental wrong with the way we're handling async db connections.
think need to look more into how this context manger thing is supposed to work

**Comment by colin-combe** [comment]
apparently we need to "Make sure the connection object returned by get_db_connection can be used with `async with`." (thats from the AI thing in my IDE)

**Comment by colin-combe** [comment]
so, the database queries were blocking and the api wasn't really working asyncronously.
@sureshhewabi - if you compare the image below to the ones we saw on Monday then you can see the quick queries now return quickly.
Screenshot from 2024-11-06 07-02-39

this wasn't anything to do with the context manager (which isn't so important), it was because we need to use the asyncpg library to make it work asyncronously.

This should improve things. Also means we can later get the advantage of the parallel load by starting to process the data as it arrives. I've got some refactoring to do then i'll update this PR.

@sureshhewabi - there's some maintenance things to look at with this project but i think you're busy testing out the validation function of xi-mzidentml-converter at the moment, so we can look at it after that.

**Comment by sureshhewabi** [comment]
> re's some maintenance things to look a

This is an excellent finding! Thanks for that.
Yes I will come back to this as soon as I am done with validation

**Comment by sureshhewabi** [comment]
Please add new library dependancies (eg:asyncpg) to setup.py as well

**Comment by colin-combe** [comment]
hi suresh,
I saw your comment about adding asyncpg to setup.py.
Can't do that 'coz there is no setup.py... i think you maybe noticed that after your comment and that's why the comment is now gone.
no setup.py is also why we don't have version numbers on this.

i think the get metadata request would benefit from being split into multiple request, like the AI suggested above.

> This is an excellent finding!

yep, now that we know the database queries weren't really asynchronous, we should be able to get things working much more reliably by fixing that.

I think we need to look at the sqlalchemy queries also, so that they are also asynchronous (at the moment i think they are not)

and possibly also looking at the writing to the database from xi-mzidentml-converter to make it async - it probably isn't and this might be why the whole system became unusable when you were parsing data

**Comment by sureshhewabi** [comment]
Yes sorry I realised it that no setup.py for this API library. Got confused with the other one

**Comment by colin-combe** [comment]
i looked into async sqlalchemy a bit yesterday (https://docs.sqlalchemy.org/en/20/orm/extensions/asyncio.html
). Its not entirely straightforward but i think it will come down to changing how sessions are created in https://github.com/PRIDE-Archive/xiview-api/blob/python3/app/config/database.py

once all the db stuff is async, we should maybe implement a connection pool, they say this is more efficient (but prob not high priority).

**Pull request merged**
